import 'package:get/get.dart';

class LanguageService implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "News": "الاخبار",
          "Weather": "الطقس",
          "Search": "البحث",
          "Browse": "تصفح",
          "Home": "الصفحة الرئيسية",
          "Notification": "الاشعارات",
          'Mode': 'وضع',
          'Dark mode': 'الوضع الليلي',
          'Language': 'الغة',
          'About': 'حول',
          'About News': 'حول الاخبار',
          'About Weather': 'حول الطقس',
          'Change Mode': 'تغير الوضع',
          'System': 'النظام',
          'Light': 'فاتح',
          'Dark': 'داكن',
          'Change Language': 'تغير اللغة',
          'English': 'أنجليزي',
          'Arabic': 'عربي',
          'Hour': 'ساعة',
          'Politics': 'سياسة',
          'Recent News': 'أخبار حديثة',
          'Breaking News': 'أخبار عاجلة',
          'No Internet connection': 'لا يوجد اتصال بالإنترنت',
          'Check your connection, then refresh the page.':
              'تحقق من اتصالك، ثم قم بتحديث الصفحة.',
          'Try Again': 'أعادة المحاولة',
          'Read More': 'اقرأ المزيد',
          'Business': 'الأعمال',
          'Entertainment': 'الترفيه',
          'General': 'عام',
          'Health': 'صحة',
          'Science': 'علوم',
          'Sports': 'رياضة',
          'Technology': 'تكنولوجيا',
          'Discover': 'يكتشف',
          'News from all over the world': 'أخبار من جميع أنحاء العالم',
          'Search...': 'أبحث...',
          'News in the world': 'الأخبار في كل العالم',
          'Al locus where you get chance to authenticate news\nto make impact on society':
              'في كل مكان حيث تحصل على فرصة لتوثيق الأخبار\nلإحداث تأثير على المجتمع',
          'Weather in the world': 'الطقس في كل العالم',
          'Discover the weather your city and plan\nyour day correctly':
              'اكتشف حالة الطقس في مدينتك وخطط\nليومك بشكل صحيح',
          'Time in the world': 'الوقت في كل العالم',
          'Discover the time of all the world': 'اكتشف الوقت في كل العالم',
          'Get Started now': 'أبدأ الآن',
          'Skip': 'تخطى',
          'Logout': 'تسجيل خروج',
          'Exit': 'الخروج',
          'No search result found': 'لم يتم العثور على نتيجة بحث',
          'Clock': 'الساعة',
          'Good Night!!': 'تصبح على خير',
          'Good Morning!!': 'صباح الخير',
          'Good Afternoon!!': 'مساء الخير',
          'Good Evening!!': 'مساء الخير',
          '°C ': 'س° ',
          'km/h': 'كم/س',
          'PM': 'م',
          'AM': 'ص',
          "Next Three Day": "بعد ثلاثة أيام",
          "Today": "اليوم",
          "Country": "الدولة",
          "Governorate": "المحافظة",
          "City": "المدينة",
          "Enter Country Name": "أدخل اسم البلد",
          "Enter Governorate Name": "أدخل اسم المحافظة",
          "Enter City Name": "أدخل اسم المدينة",
        },
        "en": {
          "Enter City Name": "Enter City Name",
          "Enter Governorate Name": "Enter Governorate Name",
          "Enter Country Name": "Enter Country Name",
          "City": "City",
          "Governorate": "Governorate",
          "Country": "Country",
          "News": "News",
          "Weather": "Weather",
          "Search": "Search",
          "Browse": "Browse",
          "Home": "Home",
          "Notification": "Notification",
          "Mode": "Mode",
          "Dark mode": "Dark mode",
          "Language": "Language",
          "About": "About",
          "About News": "About News",
          "About Weather": "About Weather",
          "Change Mode": "Change Mode",
          "System": "System",
          "Light": "Light",
          "Dark": "Dark",
          'Change Language': 'Change Language',
          'English': 'English',
          'Arabic': 'Arabic',
          'Hour': 'Hour',
          'Politics': 'Politics',
          'Recent News': 'Recent News',
          'Breaking News': 'Breaking News',
          'No Internet connection': 'No Internet connection',
          'Check your connection, then Try Again the page.':
              'Check your connection, then refresh the page.',
          'Try Again': 'Try Again',
          'Read More': 'Read More',
          'Business': 'Business',
          'Entertainment': 'Entertainment',
          'General': 'General',
          'Health': 'Health',
          'Science': 'Science',
          'Sports': 'Sports',
          'Technology': 'Technology',
          'Discover': 'Discover',
          'News from all over the world': 'News from all over the world',
          'Search...': 'Search...',
          'News in the world': 'News in the world',
          'Al locus where you get chance to authenticate news to make impact on society':
              'Al locus where you get chance to authenticate news to make impact on society',
          'Weather in the world': 'Weather in the world',
          'Discover the weather your city and plan\nyour day correctly':
              'Discover the weather your city and plan\nyour day correctly',
          'Time in the world': 'Time in the world',
          'Discover the time of all the world':
              'Discover the time of all the world',
          'Get Started now': 'Get Started now',
          'Skip': 'Skip',
          'Logout': 'Logout',
          'Exit': 'Exit',
          'No search result found': 'No search result found',
          'Clock': 'Clock',
          'Good Night!!': 'Good Night!!',
          'Good Morning!!': 'Good Morning!!',
          'Good Afternoon!!': 'Good Afternoon!!',
          'Good Evening!!': 'Good Evening!!',
          '°C ': '°C ',
          'km/h': 'km/h ',
          'PM': 'PM',
          'AM': 'AM',
          "Next Three Day": "Next Three Day",
          "Today": "Today",
        },
      };
}
